#ifndef NXOpen_MFGMODEL_BOPCONVEYOR_HXX_INCLUDED
#define NXOpen_MFGMODEL_BOPCONVEYOR_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     MfgModel_BOPConveyor.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/MfgModel_BOPBaseModel.hxx>
#include <NXOpen/libmfgmodelopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace MfgModel
    {
        class BOPConveyor;
    }
    namespace MfgModel
    {
        class BOPBaseModel;
    }
    namespace MfgModel
    {
        class _BOPConveyorBuilder;
        class BOPConveyorImpl;

        /// \cond NX_NO_DOC 
        /** Represents BOPConveyor Instance 
         <br>  Created in NX1847.0.0.  <br>  
        */
        class MFGMODELOPENCPPEXPORT  BOPConveyor : public NXOpen::MfgModel::BOPBaseModel
        {
            private: BOPConveyorImpl * m_bopconveyor_impl;
            private: friend class  _BOPConveyorBuilder;
            protected: BOPConveyor();
            public: ~BOPConveyor();
        };

        /// \endcond 
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
