#ifndef NXOpen_FEATURES_VEHICLEDESIGN_PEDESTRIANPROTECTIONBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_VEHICLEDESIGN_PEDESTRIANPROTECTIONBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_VehicleDesign_PedestrianProtectionBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_FeatureBuilder.hxx>
#include <NXOpen/Features_VehicleDesign_PedestrianProtectionBuilder.hxx>
#include <NXOpen/Section.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace VehicleDesign
        {
            class PedestrianProtectionBuilder;
        }
    }
    class Expression;
    namespace Features
    {
        class FeatureBuilder;
    }
    class NXColor;
    class Plane;
    class Point;
    class Section;
    class SelectDisplayableObjectList;
    namespace Features
    {
        namespace VehicleDesign
        {
            class _PedestrianProtectionBuilderBuilder;
            class PedestrianProtectionBuilderImpl;
            /**
                    Represents a @link Features::VehicleDesign::PedestrianProtection Features::VehicleDesign::PedestrianProtection@endlink  builder
                     <br> To create a new instance of this class, use @link Features::VehicleDesignCollection::CreatePedestrianProtectionBuilder  Features::VehicleDesignCollection::CreatePedestrianProtectionBuilder @endlink  <br> 
            Default values.
            <table border="1"> 
             
            <tr><th> 
            Property</th>  <th> 
            Value</th> </tr>
            <tr><td> 
             
            AdultHic1000Angle.Value </td> <td> 
             
            50 </td> </tr> 

            <tr><td> 
             
            AdultHic1000Offset.Value (deprecated) </td> <td> 
             
            95 (millimeters part), 3.7 (inches part) </td> </tr> 

            <tr><td> 
             
            AdultHic1000OutputFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            AdultHic1000OutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            AdultHic1000OutputWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            AdultHic1700Angle.Value </td> <td> 
             
            50 </td> </tr> 

            <tr><td> 
             
            AdultHic1700Offset.Value (deprecated) </td> <td> 
             
            74 (millimeters part), 2.9 (inches part) </td> </tr> 

            <tr><td> 
             
            AdultHic1700OutputFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            AdultHic1700OutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            AdultHic1700OutputWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            ChildHic1000Angle.Value </td> <td> 
             
            65 </td> </tr> 

            <tr><td> 
             
            ChildHic1000Offset.Value (deprecated) </td> <td> 
             
            85 (millimeters part), 3.3 (inches part) </td> </tr> 

            <tr><td> 
             
            ChildHic1000OutputFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            ChildHic1000OutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            ChildHic1000OutputWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            ChildHic1700Angle.Value </td> <td> 
             
            65 </td> </tr> 

            <tr><td> 
             
            ChildHic1700Offset.Value (deprecated) </td> <td> 
             
            68 (millimeters part), 2.7 (inches part) </td> </tr> 

            <tr><td> 
             
            ChildHic1700OutputFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            ChildHic1700OutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            ChildHic1700OutputWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            ConstructGeometryFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            ConstructGeometryLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            ConstructGeometryWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            CornerBumperAngle.Value </td> <td> 
             
            30 </td> </tr> 

            <tr><td> 
             
            CornerBumperAngleMarginal.Value </td> <td> 
             
            32 </td> </tr> 

            <tr><td> 
             
            CreateHeadImpactZones </td> <td> 
             
            1 </td> </tr> 

            <tr><td> 
             
            CreateImpactGrid </td> <td> 
             
            1 </td> </tr> 

            <tr><td> 
             
            CreateLegImpact </td> <td> 
             
            1 </td> </tr> 

            <tr><td> 
             
            CreateReferenceLines </td> <td> 
             
            1 </td> </tr> 

            <tr><td> 
             
            CreateWrapAroundDistanceLines </td> <td> 
             
            1 </td> </tr> 

            <tr><td> 
             
            DisplayConstructionGeometry </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            DisplayDeletedGridPoints </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            DisplayInterferenceResult </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            FrontRefAngle.Value </td> <td> 
             
            40 </td> </tr> 

            <tr><td> 
             
            FrontRefAngleMarginal.Value </td> <td> 
             
            38 </td> </tr> 

            <tr><td> 
             
            FrontRefAngleNcap.Value </td> <td> 
             
            50 </td> </tr> 

            <tr><td> 
             
            GridAdultFullOutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            GridAdultPartialOutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            GridChildFullOutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            GridChildPartialOutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            GridNCAP1000OutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            GridNCAP1350OutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            GridNCAP1700OutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            GridNCAP650OutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            GridOutputFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            GridOutputWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            HeadDiameter.Value </td> <td> 
             
            165 (millimeters part), 6.5 (inches part) </td> </tr> 

            <tr><td> 
             
            HeadDiameterMarginal.Value </td> <td> 
             
            145 (millimeters part), 5.7 (inches part) </td> </tr> 

            <tr><td> 
             
            HingeDistance.Value </td> <td> 
             
            0 (millimeters part), 0 (inches part) </td> </tr> 

            <tr><td> 
             
            InterferenceFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            InterferenceLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            InterferenceWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            LegZonesOutputFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            LegZonesOutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            LegZonesOutputWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            LowerBumperAngle.Value </td> <td> 
             
            20 </td> </tr> 

            <tr><td> 
             
            MirrorFaces (deprecated) </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            PopupDistance.Value </td> <td> 
             
            120 (millimeters part), 4.7 (inches part) </td> </tr> 

            <tr><td> 
             
            ProcessActiveHood </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            ReferenceOutputFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            ReferenceOutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            ReferenceOutputWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            RodDiameter.Value </td> <td> 
             
            50 (millimeters part), 2 (inches part) </td> </tr> 

            <tr><td> 
             
            SideRefAngle.Value </td> <td> 
             
            45 </td> </tr> 

            <tr><td> 
             
            SideRefAngleMarginal.Value </td> <td> 
             
            47 </td> </tr> 

            <tr><td> 
             
            SideRefAngleNcap.Value </td> <td> 
             
            45 </td> </tr> 

            <tr><td> 
             
            Standard </td> <td> 
             
            NorthAmerican </td> </tr> 

            <tr><td> 
             
            StepDistance.Value </td> <td> 
             
            50 (millimeters part), 2 (inches part) </td> </tr> 

            <tr><td> 
             
            TransformMethod </td> <td> 
             
            Translation </td> </tr> 

            <tr><td> 
             
            UpperBumperAngle.Value </td> <td> 
             
            25 </td> </tr> 

            <tr><td> 
             
            UseMarginal </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            WadBoundaryValue </td> <td> 
             
            Fourth </td> </tr> 

            <tr><td> 
             
            WadEndValue </td> <td> 
             
            Sixth </td> </tr> 

            <tr><td> 
             
            WadOutputFont </td> <td> 
             
            Solid </td> </tr> 

            <tr><td> 
             
            WadOutputLayer </td> <td> 
             
            0 </td> </tr> 

            <tr><td> 
             
            WadOutputWidth </td> <td> 
             
            Normal </td> </tr> 

            <tr><td> 
             
            WadStartValue </td> <td> 
             
            First </td> </tr> 

            </table>  

             <br>  Created in NX6.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  PedestrianProtectionBuilder : public Features::FeatureBuilder
            {
                /** Settings for the type of pedestrian protection impact study. */
                public: enum Types
                {
                    TypesHeadAndLegImpact/** Head and leg impact study. */,
                    TypesHeadImpact/** Head impact study only. */,
                    TypesLegImpact/** Leg impact study only. */
                };

                /** Settings for the type of pedestrian protection standard to use in the study. */
                public: enum StandardType
                {
                    StandardTypeNorthAmerican/** North american standard */,
                    StandardTypeEuropean/** European standard */,
                    StandardTypeJapanese/** Japanese standard */,
                    StandardTypeKorean/** Korean standard */,
                    StandardTypeChinese/** Chinese standard */
                };

                /** Settings for the start, end and boundary wrap around distance line to create. */
                public: enum Wad
                {
                    WadFirst/** First wrap around distance line. */,
                    WadSecond/** Second wrap around distance line. */,
                    WadThird/** Third wrap around distance line. */,
                    WadFourth/** Fourth wrap around distance line. */,
                    WadFifth/** Fifth wrap around distance line. */,
                    WadSixth/** Sixth wrap around distance line. Not valid for boundary. */
                };

                /** Settings for font to create the various output with. */
                public: enum Font
                {
                    FontDefault/** Default Font. */,
                    FontSolid/** Solid Font. */,
                    FontDashed/** Dashed Font. */,
                    FontPhantom/** Phantom Font. */,
                    FontCenterline/** Centerline Font. */,
                    FontDotted/** Dotted Font. */,
                    FontLongDashed/** LongDashed Font. */,
                    FontDottedDashed/** DottedDashed Font. */
                };

                /** Settings for width to create the various output with. */
                public: enum Width
                {
                    WidthDefault/**Default Width*/,
                    WidthNormal/**normal Width*/,
                    WidthThick/**Thick width*/,
                    WidthThin/**Thin width*/
                };

                /** Settings for the transform method of pedestrian protection active hood system. */
                public: enum TransformMethods
                {
                    TransformMethodsTranslation/** Translation method. */,
                    TransformMethodsRotation/** Rotation method. */
                };

                private: PedestrianProtectionBuilderImpl * m_pedestrianprotectionbuilder_impl;
                private: friend class  _PedestrianProtectionBuilderBuilder;
                protected: PedestrianProtectionBuilder();
                public: ~PedestrianProtectionBuilder();
                /**Returns  the standard that should be used in the analysis. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::StandardType Standard
                (
                );
                /**Sets  the standard that should be used in the analysis. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetStandard
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::StandardType setStandard /** setstandard */ 
                );
                /**Returns  the ground plane. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Plane * Plane
                (
                );
                /**Sets  the ground plane. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetPlane
                (
                    NXOpen::Plane * plane /** plane */ 
                );
                /**Returns  the collector containing the faces of the bonnet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectDisplayableObjectList * BonnetTop
                (
                );
                /**Returns  the collector containing the faces of the bonnet that are not to be mirrored. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectDisplayableObjectList * BonnetTopNotMirrored
                (
                );
                /**Returns  the collector containing the faces of the windshield. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectDisplayableObjectList * Windshield
                (
                );
                /**Returns  the collector containing the faces of the active hood. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectDisplayableObjectList * Hood
                (
                );
                /**Returns  the point about which to rotate the active hood. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Point * HingePoint
                (
                );
                /**Sets  the point about which to rotate the active hood. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetHingePoint
                (
                    NXOpen::Point * hingePoint /** hingepoint */ 
                );
                /**Returns  the reference point of the active hood. At this point the active hood will be rotated
                                about the hinge point so that this point is moved the popup distance in the +Z direction. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Point * PopupPoint
                (
                );
                /**Sets  the reference point of the active hood. At this point the active hood will be rotated
                                about the hinge point so that this point is moved the popup distance in the +Z direction. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetPopupPoint
                (
                    NXOpen::Point * popupPoint /** popuppoint */ 
                );
                /**Returns  the distance to move the reference point of the active hood. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * PopupDistance
                (
                );
                /**Returns  the transform method that should be used in active hood system. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::TransformMethods TransformMethod
                (
                );
                /**Sets  the transform method that should be used in active hood system. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetTransformMethod
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::TransformMethods transformMethod /** transformmethod */ 
                );
                /**Returns  the distance to move the reference point of the active hood. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * HingeDistance
                (
                );
                /**Returns  the collector containing the faces and facetted bodies of the A-Pillar. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectDisplayableObjectList * APillar
                (
                );
                /**Returns  the list of the components to check interference with the impact sheets. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectDisplayableObjectList * Component
                (
                );
                /**Returns  the upper leg impact locations.  
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Section * UpperLegPositions
                (
                );
                /**Returns  the setting to indicate if the bonnet, windshield and hood faces should be mirrored
                                before performing the analysis,
                                true they will be mirrored, false they will not be mirrored.  
                 <br>  @deprecated Deprecated in NX9.0.0.  This API is no longer used. <br>  

                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public:  NX_DEPRECATED("Deprecated in NX9.0.0.  This API is no longer used.") bool MirrorFaces
                (
                );
                /**Sets  the setting to indicate if the bonnet, windshield and hood faces should be mirrored
                                before performing the analysis,
                                true they will be mirrored, false they will not be mirrored.  
                 <br>  @deprecated Deprecated in NX9.0.0.  This API is no longer used. <br>  

                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public:  NX_DEPRECATED("Deprecated in NX9.0.0.  This API is no longer used.") void SetMirrorFaces
                (
                    bool mirrorFaces /** mirrorfaces */ 
                );
                /**Returns  the setting to indicate if the wrap around distance lines should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool CreateWrapAroundDistanceLines
                (
                );
                /**Sets  the setting to indicate if the wrap around distance lines should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetCreateWrapAroundDistanceLines
                (
                    bool wad /** wad */ 
                );
                /**Returns  the setting to indicate if the reference lines should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool CreateReferenceLines
                (
                );
                /**Sets  the setting to indicate if the reference lines should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetCreateReferenceLines
                (
                    bool referenceLines /** referencelines */ 
                );
                /**Returns  the setting to indicate if the adult and child head impact sheets should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool CreateHeadImpactZones
                (
                );
                /**Sets  the setting to indicate if the adult and child head impact sheets should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetCreateHeadImpactZones
                (
                    bool headImpactZones /** headimpactzones */ 
                );
                /**Returns  the setting to indicate if the leg impact curves should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool CreateLegImpact
                (
                );
                /**Sets  the setting to indicate if the leg impact curves should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetCreateLegImpact
                (
                    bool legImpact /** legimpact */ 
                );
                /**Returns  the setting to indicate if the interference curves should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool DisplayInterferenceResult
                (
                );
                /**Sets  the setting to indicate if the interference curves should be created, 
                                true they will be created, false they will not be created.  
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetDisplayInterferenceResult
                (
                    bool displayInterferenceResult /** displayinterferenceresult */ 
                );
                /**Returns  the setting to indicate if the construction geometry should be created, 
                                true they will be created, false they will not be created. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool DisplayConstructionGeometry
                (
                );
                /**Sets  the setting to indicate if the construction geometry should be created, 
                                true they will be created, false they will not be created. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetDisplayConstructionGeometry
                (
                    bool displayConstructionGeometry /** displayconstructiongeometry */ 
                );
                /**Returns  the setting to indicate if the marginal values should be used when creating the impact zone, 
                                true they will be used, false they will not be used. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool UseMarginal
                (
                );
                /**Sets  the setting to indicate if the marginal values should be used when creating the impact zone, 
                                true they will be used, false they will not be used. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetUseMarginal
                (
                    bool useMarginal /** usemarginal */ 
                );
                /**Returns  the setting to indicate if the active hood should be analyzed, 
                                true it will be used, false it will not be used. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool ProcessActiveHood
                (
                );
                /**Sets  the setting to indicate if the active hood should be analyzed, 
                                true it will be used, false it will not be used. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetProcessActiveHood
                (
                    bool processActiveHood /** processactivehood */ 
                );
                /**Returns  the setting to indicate if the deleted grid points should be displayed, 
                                true they will be displayed, false they will not be displayed. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: bool DisplayDeletedGridPoints
                (
                );
                /**Sets  the setting to indicate if the deleted grid points should be displayed, 
                                true they will be displayed, false they will not be displayed. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetDisplayDeletedGridPoints
                (
                    bool displayDeletedGridPoints /** displaydeletedgridpoints */ 
                );
                /**Returns  the setting to indicate if the impact grid should be created, 
                                true it will be created, false it will not be created. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: bool CreateImpactGrid
                (
                );
                /**Sets  the setting to indicate if the impact grid should be created, 
                                true it will be created, false it will not be created. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetCreateImpactGrid
                (
                    bool createImpactGrid /** createimpactgrid */ 
                );
                /**Returns  the type of impact study to perform. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Types Type
                (
                );
                /**Sets  the type of impact study to perform. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetType
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Types type /** type */ 
                );
                /**Returns  the distance between sections used in the analysis. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * StepDistance
                (
                );
                /**Returns  the diameter of the headform. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * HeadDiameter
                (
                );
                /**Returns  the marginal diameter of the headform. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * HeadDiameterMarginal
                (
                );
                /**Returns  the testing rod diameter of the leg impact. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * RodDiameter
                (
                );
                /**Returns  the leg impact spreadsheet file. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXString LegSpreadsheet
                (
                );
                /**Sets  the leg impact spreadsheet file. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetLegSpreadsheet
                (
                    const NXString & legSpreadsheet /** legspreadsheet */ 
                );
                /**Sets  the leg impact spreadsheet file. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                void SetLegSpreadsheet
                (
                    const char * legSpreadsheet /** legspreadsheet */ 
                );
                /**Returns  the first wrap around distance line to create. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Wad WadStartValue
                (
                );
                /**Sets  the first wrap around distance line to create. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetWadStartValue
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Wad wadstartenum /** wadstartenum */ 
                );
                /**Returns  the last wrap around distance line to create. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Wad WadEndValue
                (
                );
                /**Sets  the last wrap around distance line to create. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetWadEndValue
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Wad wadendenum /** wadendenum */ 
                );
                /**Returns  the wrap around distance line to use as the boundary between the adult and child zones. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Wad WadBoundaryValue
                (
                );
                /**Sets  the wrap around distance line to use as the boundary between the adult and child zones. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetWadBoundaryValue
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Wad wadboundaryenum /** wadboundaryenum */ 
                );
                /**Returns  the angle that is used to determine the front reference line. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * FrontRefAngle
                (
                );
                /**Returns  the marginal angle that is used to determine the front reference line. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * FrontRefAngleMarginal
                (
                );
                /**Returns  the European NCAP (New Car Assessment Program) angle that is used to determine the front reference line. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * FrontRefAngleNcap
                (
                );
                /**Returns  the European NCAP (New Car Assessment Program) marginal angle that is used to determine the front reference line. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * FrontRefAngleNcapMarginal
                (
                );
                /**Returns  the angle that is used to determine the side reference line. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * SideRefAngle
                (
                );
                /**Returns  the marginal angle that is used to determine the side reference line. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * SideRefAngleMarginal
                (
                );
                /**Returns  the European NCAP (New Car Assessment Program) angle that is used to determine the side reference line. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * SideRefAngleNcap
                (
                );
                /**Returns  the European NCAP (New Car Assessment Program) angle that is used to determine the side reference line. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * SideRefAngleNcapMarginal
                (
                );
                /**Returns  the angle to translate the adult HIC (Head Injury Criterion) 1000 impact sheet and grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * AdultHic1000Angle
                (
                );
                /**Returns  the distance to translate the adult HIC (Head Injury Criterion) 1000 impact sheet and grid. 
                 <br>  @deprecated Deprecated in NX9.0.0.  The offset value will be retrieved from the physical material property. <br>  

                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public:  NX_DEPRECATED("Deprecated in NX9.0.0.  The offset value will be retrieved from the physical material property.") NXOpen::Expression * AdultHic1000Offset
                (
                );
                /**Returns  the angle to translate the adult HIC (Head Injury Criterion) 1700 impact sheet and grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * AdultHic1700Angle
                (
                );
                /**Returns  the distance to translate the adult HIC (Head Injury Criterion) 1700 impact sheet and grid. 
                 <br>  @deprecated Deprecated in NX9.0.0.  The offset value will be retrieved from the physical material property. <br>  

                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public:  NX_DEPRECATED("Deprecated in NX9.0.0.  The offset value will be retrieved from the physical material property.") NXOpen::Expression * AdultHic1700Offset
                (
                );
                /**Returns  the angle to translate the child HIC (Head Injury Criterion) 1000 impact sheet and grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * ChildHic1000Angle
                (
                );
                /**Returns  the distance to translate the child HIC (Head Injury Criterion) 1000 impact sheet and grid. 
                 <br>  @deprecated Deprecated in NX9.0.0.  The offset value will be retrieved from the physical material property. <br>  

                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public:  NX_DEPRECATED("Deprecated in NX9.0.0.  The offset value will be retrieved from the physical material property.") NXOpen::Expression * ChildHic1000Offset
                (
                );
                /**Returns  the angle to translate the child HIC (Head Injury Criterion) 1700 impact sheet and grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * ChildHic1700Angle
                (
                );
                /**Returns  the distance to translate the child HIC (Head Injury Criterion) 1700 impact sheet and grid. 
                 <br>  @deprecated Deprecated in NX9.0.0.  The offset value will be retrieved from the physical material property. <br>  

                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public:  NX_DEPRECATED("Deprecated in NX9.0.0.  The offset value will be retrieved from the physical material property.") NXOpen::Expression * ChildHic1700Offset
                (
                );
                /**Returns  the angle that is used to determine the upper limit of the bumper. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * UpperBumperAngle
                (
                );
                /**Returns  the angle that is used to determine the lower limit of the bumper. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * LowerBumperAngle
                (
                );
                /**Returns  the angle that is used to determine the corner of the bumper. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * CornerBumperAngle
                (
                );
                /**Returns  the marginal angle that is used to determine the corner of the bumper. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Expression * CornerBumperAngleMarginal
                (
                );
                /**Returns  the score value is used to check NCAP 650 offset interference. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: double GridNcap650OffsetScore
                (
                );
                /**Returns  the score value is used to check NCAP 1000 offset interference. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: double GridNcap1000OffsetScore
                (
                );
                /**Returns  the score value is used to check NCAP 1350 offset interference. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: double GridNcap1350OffsetScore
                (
                );
                /**Returns  the score value is used to check NCAP 1700 offset interference. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: double GridNcap1700OffsetScore
                (
                );
                /**Returns  the score value is used to check NCAP untranslated interference. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: double GridNcapUntranslatedScore
                (
                );
                /**Returns  the color that will be used for the wrap around distance lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * WadOutputColor
                (
                );
                /**Sets  the color that will be used for the wrap around distance lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetWadOutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the wrap around distance lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font WadOutputFont
                (
                );
                /**Sets  the font that will be used for the wrap around distance lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetWadOutputFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the wrap around distance lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int WadOutputLayer
                (
                );
                /**Sets  the layer that will be used for the wrap around distance lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetWadOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the wrap around distance lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width WadOutputWidth
                (
                );
                /**Sets  the line width that will be used for the wrap around distance lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetWadOutputWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the reference lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * ReferenceOutputColor
                (
                );
                /**Sets  the color that will be used for the reference lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetReferenceOutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the reference lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font ReferenceOutputFont
                (
                );
                /**Sets  the font that will be used for the reference lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetReferenceOutputFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the reference lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int ReferenceOutputLayer
                (
                );
                /**Sets  the layer that will be used for the reference lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetReferenceOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the reference lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width ReferenceOutputWidth
                (
                );
                /**Sets  the line width that will be used for the reference lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetReferenceOutputWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the adult HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * AdultHic1000OutputColor
                (
                );
                /**Sets  the color that will be used for the adult HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetAdultHic1000OutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the adult HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font AdultHic1000OutputFont
                (
                );
                /**Sets  the font that will be used for the adult HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetAdultHic1000OutputFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the adult HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int AdultHic1000OutputLayer
                (
                );
                /**Sets  the layer that will be used for the adult HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetAdultHic1000OutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the adult HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width AdultHic1000OutputWidth
                (
                );
                /**Sets  the line width that will be used for the adult HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetAdultHic1000OutputWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the adult HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * AdultHic1700OutputColor
                (
                );
                /**Sets  the color that will be used for the adult HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetAdultHic1700OutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the adult HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font AdultHic1700OutputFont
                (
                );
                /**Sets  the font that will be used for the adult HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetAdultHic1700OutputFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the adult HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int AdultHic1700OutputLayer
                (
                );
                /**Sets  the layer that will be used for the adult HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetAdultHic1700OutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the adult HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width AdultHic1700OutputWidth
                (
                );
                /**Sets  the line width that will be used for the adult HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetAdultHic1700OutputWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the child HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * ChildHic1000OutputColor
                (
                );
                /**Sets  the color that will be used for the child HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetChildHic1000OutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the child HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font ChildHic1000OutputFont
                (
                );
                /**Sets  the font that will be used for the child HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetChildHic1000OutputFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the child HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int ChildHic1000OutputLayer
                (
                );
                /**Sets  the layer that will be used for the child HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetChildHic1000OutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the child HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width ChildHic1000OutputWidth
                (
                );
                /**Sets  the line width that will be used for the child HIC (Head Injury Criterion) 1000 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetChildHic1000OutputWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the child HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * ChildHic1700OutputColor
                (
                );
                /**Sets  the color that will be used for the child HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetChildHic1700OutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the child HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font ChildHic1700OutputFont
                (
                );
                /**Sets  the font that will be used for the child HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetChildHic1700OutputFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the child HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int ChildHic1700OutputLayer
                (
                );
                /**Sets  the layer that will be used for the child HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetChildHic1700OutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the child HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width ChildHic1700OutputWidth
                (
                );
                /**Sets  the line width that will be used for the child HIC (Head Injury Criterion) 1700 impact sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetChildHic1700OutputWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the leg impact zone lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * LegZonesOutputColor
                (
                );
                /**Sets  the color that will be used for the leg impact zone lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetLegZonesOutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the leg impact zone lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font LegZonesOutputFont
                (
                );
                /**Sets  the font that will be used for the leg impact zone lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetLegZonesOutputFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the leg impact zone lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int LegZonesOutputLayer
                (
                );
                /**Sets  the layer that will be used for the leg impact zone lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetLegZonesOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the layer that will be used for the upper leg impact zone. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: int UpperLegZonesOutputLayer
                (
                );
                /**Sets  the layer that will be used for the upper leg impact zone. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetUpperLegZonesOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the leg impact zone lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width LegZonesOutputWidth
                (
                );
                /**Sets  the line width that will be used for the leg impact zone lines. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetLegZonesOutputWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the interference curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * InterferenceColor
                (
                );
                /**Sets  the color that will be used for the interference curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetInterferenceColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the interference curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font InterferenceFont
                (
                );
                /**Sets  the font that will be used for the interference curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetInterferenceFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the interference curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int InterferenceLayer
                (
                );
                /**Sets  the layer that will be used for the interference curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetInterferenceLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the interference curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width InterferenceWidth
                (
                );
                /**Sets  the line width that will be used for the interference curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetInterferenceWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the various construction curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * ConstructGeometryColor
                (
                );
                /**Sets  the color that will be used for the various construction curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetConstructGeometryColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the various construction curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font ConstructGeometryFont
                (
                );
                /**Sets  the font that will be used for the various construction curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetConstructGeometryFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the layer that will be used for the various construction curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int ConstructGeometryLayer
                (
                );
                /**Sets  the layer that will be used for the various construction curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetConstructGeometryLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the line width that will be used for the various construction curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width ConstructGeometryWidth
                (
                );
                /**Sets  the line width that will be used for the various construction curves. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetConstructGeometryWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the color that will be used for the passing areas of the NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridPassColor
                (
                );
                /**Sets  the color that will be used for the passing areas of the NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridPassColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the color that will be used for the warning areas of the NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridWarningColor
                (
                );
                /**Sets  the color that will be used for the warning areas of the NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridWarningColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the color that will be used for the failing areas of the NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridFailColor
                (
                );
                /**Sets  the color that will be used for the failing areas of the NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridFailColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the font that will be used for the European NCAP (New Car Assessment Program) grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font GridOutputFont
                (
                );
                /**Sets  the font that will be used for the European NCAP (New Car Assessment Program) grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridOutputFont
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Font font /** font */ 
                );
                /**Returns  the line width that will be used for the NCAP (New Car Assessment Program) grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width GridOutputWidth
                (
                );
                /**Sets  the line width that will be used for the NCAP (New Car Assessment Program) grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridOutputWidth
                (
                    NXOpen::Features::VehicleDesign::PedestrianProtectionBuilder::Width width /** width */ 
                );
                /**Returns  the layer that will be used for the NCAP (New Car Assessment Program) adult full grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridAdultFullOutputLayer
                (
                );
                /**Sets  the layer that will be used for the NCAP (New Car Assessment Program) adult full grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridAdultFullOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the layer that will be used for the NCAP (New Car Assessment Program) adult partial grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridAdultPartialOutputLayer
                (
                );
                /**Sets  the layer that will be used for the NCAP (New Car Assessment Program) adult partial grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridAdultPartialOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the layer that will be used for the NCAP (New Car Assessment Program) child full grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridChildFullOutputLayer
                (
                );
                /**Sets  the layer that will be used for the NCAP (New Car Assessment Program) child full grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridChildFullOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the layer that will be used for the NCAP (New Car Assessment Program) child partial grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridChildPartialOutputLayer
                (
                );
                /**Sets  the layer that will be used for the NCAP (New Car Assessment Program) child partial grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridChildPartialOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the color that will be used for the European NCAP (New Car Assessment Program) 650 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridNCAP650OutputColor
                (
                );
                /**Sets  the color that will be used for the European NCAP (New Car Assessment Program) 650 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAP650OutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the layer that will be used for the European NCAP (New Car Assessment Program) 650 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridNCAP650OutputLayer
                (
                );
                /**Sets  the layer that will be used for the European NCAP (New Car Assessment Program) 650 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAP650OutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the color that will be used for the European NCAP (New Car Assessment Program) 1000 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridNCAP1000OutputColor
                (
                );
                /**Sets  the color that will be used for the European NCAP (New Car Assessment Program) 1000 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAP1000OutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the layer that will be used for the European NCAP (New Car Assessment Program) 1000 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridNCAP1000OutputLayer
                (
                );
                /**Sets  the layer that will be used for the European NCAP (New Car Assessment Program) 1000 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAP1000OutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the color that will be used for the European NCAP (New Car Assessment Program) 1350 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridNCAP1350OutputColor
                (
                );
                /**Sets  the color that will be used for the European NCAP (New Car Assessment Program) 1350 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAP1350OutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the layer that will be used for the European NCAP (New Car Assessment Program) 1350 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridNCAP1350OutputLayer
                (
                );
                /**Sets  the layer that will be used for the European NCAP (New Car Assessment Program) 1350 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAP1350OutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the color that will be used for the European NCAP (New Car Assessment Program) 1700 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridNCAP1700OutputColor
                (
                );
                /**Sets  the color that will be used for the European NCAP (New Car Assessment Program) 1700 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAP1700OutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the layer that will be used for the European NCAP (New Car Assessment Program) 1700 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridNCAP1700OutputLayer
                (
                );
                /**Sets  the layer that will be used for the European NCAP (New Car Assessment Program) 1700 offset grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAP1700OutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the color that will be used for the European NCAP (New Car Assessment Program) untranslated grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridNCAPUntranslatedOutputColor
                (
                );
                /**Sets  the color that will be used for the European NCAP (New Car Assessment Program) untranslated grid sheet. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridNCAPUntranslatedOutputColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the layer that will be used for the NCAP (New Car Assessment Program) untranslated grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : None */
                public: int GridUntranslatedOutputLayer
                (
                );
                /**Sets  the layer that will be used for the NCAP (New Car Assessment Program) untranslated grid sheet. 
                 <br>  Created in NX6.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridUntranslatedOutputLayer
                (
                    int layer /** layer */ 
                );
                /**Returns  the color that will be used for the headform grid points of the European NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * GridPointsColor
                (
                );
                /**Sets  the color that will be used for the headform grid points of the European NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetGridPointsColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
                /**Returns  the color that will be used for the headform deleted points of the European NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::NXColor * DeletedPointsColor
                (
                );
                /**Sets  the color that will be used for the headform deleted points of the European NCAP (New Car Assessment Program) grid. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_general_packaging ("NX General Packaging") */
                public: void SetDeletedPointsColor
                (
                    NXOpen::NXColor * color /** color */ 
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
