#ifndef NXOpen_CAE_MANUALNODEASSOCIATIONBUILDER_HXX_INCLUDED
#define NXOpen_CAE_MANUALNODEASSOCIATIONBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_ManualNodeAssociationBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_ManualNodeAssociationBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        class ManualNodeAssociationBuilder;
    }
    class Builder;
    namespace CAE
    {
        class SelectFENodeList;
    }
    class SelectTaggedObjectList;
    namespace CAE
    {
        class _ManualNodeAssociationBuilderBuilder;
        class ManualNodeAssociationBuilderImpl;
        /**
            Represents a @link NXOpen::CAE::ManualNodeAssociationBuilder NXOpen::CAE::ManualNodeAssociationBuilder@endlink 
             <br> To create a new instance of this class, use @link NXOpen::CAE::NodeElementManager::CreateManualNodeAssociationBuilder  NXOpen::CAE::NodeElementManager::CreateManualNodeAssociationBuilder @endlink  <br> 
         <br>  Created in NX10.0.0.  <br>  
        */
        class NXOPENCPP_CAEEXPORT  ManualNodeAssociationBuilder : public NXOpen::Builder
        {
            private: ManualNodeAssociationBuilderImpl * m_manualnodeassociationbuilder_impl;
            private: friend class  _ManualNodeAssociationBuilderBuilder;
            protected: ManualNodeAssociationBuilder();
            public: ~ManualNodeAssociationBuilder();
            /**Returns  the selected mesh 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::CAE::SelectFENodeList * NodeSelection
            (
            );
            /**Returns  the selected body object 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectTaggedObjectList * GeomSelection
            (
            );
            /**Returns  the flag which decides whether node association to child geometry should be done automatically or not 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: bool ChildrenGeomAssociation
            (
            );
            /**Sets  the flag which decides whether node association to child geometry should be done automatically or not 
             <br>  Created in NX10.0.0.  <br>  
             <br> License requirements : None */
            public: void SetChildrenGeomAssociation
            (
                bool bChildGeom /** bchildgeom */ 
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
