#ifndef NXOpen_FEATURES_SHIPDESIGN_EXAMINESTEELFEATUREBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHIPDESIGN_EXAMINESTEELFEATUREBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_ShipDesign_ExamineSteelFeatureBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_ShipDesign_ExamineSteelFeatureBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace ShipDesign
        {
            class ExamineSteelFeatureBuilder;
        }
    }
    class Builder;
    class SelectDisplayableObjectList;
    namespace Features
    {
        namespace ShipDesign
        {
            /** Represents the object types to examine. */
            enum ExamineSteelFeatureBuilderCheck
            {
                ExamineSteelFeatureBuilderCheckProfileWidth/** Check profile width  */,
                ExamineSteelFeatureBuilderCheckCutoutToHole/** Check cutout to hole  */,
                ExamineSteelFeatureBuilderCheckCutoutToSeam/** In basic design,check cutout to seam,In detail design,check cutout to edge */,
                ExamineSteelFeatureBuilderCheckCutoutClearance/** Check cutout top and bottom clearance*/,
                ExamineSteelFeatureBuilderCheckCutoutAngle/** Check profile cutout angle offset*/,
                ExamineSteelFeatureBuilderCheckStandardInterference/** Check standard part interference*/,
                ExamineSteelFeatureBuilderCheckCollarPlateToSeam/** In basic design,check collar plate to seam,In detail design,check collar plate to edge */,
                ExamineSteelFeatureBuilderCheckCollarPlateToHole/** Check collar plate to hole */,
                ExamineSteelFeatureBuilderCheckWideCollarPlate/** Check wide collar plate  */,
                ExamineSteelFeatureBuilderCheckNumChecks/** Number of check */
            };

            /** Represents the status of examining result. */
            enum ExamineSteelFeatureBuilderResult
            {
                ExamineSteelFeatureBuilderResultNoCheck/** No check  */,
                ExamineSteelFeatureBuilderResultPass/** All pass  */,
                ExamineSteelFeatureBuilderResultFail/** No pass  */,
                ExamineSteelFeatureBuilderResultNoResult/** Check but can't find check items  */
            };

        }
    }
    namespace Features
    {
        namespace ShipDesign
        {
            class _ExamineSteelFeatureBuilderBuilder;
            class ExamineSteelFeatureBuilderImpl;
            /** Represents the examine steel feature builder to examine steel feature.  <br> To create a new instance of this class, use @link NXOpen::Features::ShipCollection::CreateExamineSteelFeatureBuilder  NXOpen::Features::ShipCollection::CreateExamineSteelFeatureBuilder @endlink  <br> 
             <br>  Created in NX9.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  ExamineSteelFeatureBuilder : public NXOpen::Builder
            {
                private: ExamineSteelFeatureBuilderImpl * m_examinesteelfeaturebuilder_impl;
                private: friend class  _ExamineSteelFeatureBuilderBuilder;
                protected: ExamineSteelFeatureBuilder();
                public: ~ExamineSteelFeatureBuilder();
                /**Returns  the Examining objects. 
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectDisplayableObjectList * SelectObject
                (
                );
                /**Set the flag to indicate whether or not to examine the specific object type.
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") OR nx_ship_basic ("Ship Basic Design") */
                public: void SetCheck
                (
                    NXOpen::Features::ShipDesign::ExamineSteelFeatureBuilderCheck check /** Type of Check */,
                    bool status /** status */ 
                );
                /**Get the Examining status. @return  
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") OR nx_ship_basic ("Ship Basic Design") */
                public: NXOpen::Features::ShipDesign::ExamineSteelFeatureBuilderResult GetCheckResult
                (
                    NXOpen::Features::ShipDesign::ExamineSteelFeatureBuilderCheck check /** Type of Check */
                );
                /**Highlights or unhighlights the geometries in graphic to display the check result.
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") OR nx_ship_basic ("Ship Basic Design") */
                public: void HighlightCheckResult
                (
                    NXOpen::Features::ShipDesign::ExamineSteelFeatureBuilderCheck check /** Type of Check */,
                    bool highlight /** highlight */ 
                );
                /**Examines the selected objects.
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_ship_basic ("Ship Basic Design") OR nx_ship_detail ("Ship Detail Design") */
                public: void Examine
                (
                );
                /**Displays the Examining results in the information window.
                 <br>  Created in NX9.0.0.  <br>  
                 <br> License requirements : nx_ship_basic ("Ship Basic Design") OR nx_ship_detail ("Ship Detail Design") */
                public: void DisplayInformation
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
