#ifndef NXOpen_FEATURES_SHIPDESIGN_STEELINSULATIONBOUNDARYBUILDER_HXX_INCLUDED
#define NXOpen_FEATURES_SHIPDESIGN_STEELINSULATIONBOUNDARYBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_ShipDesign_SteelInsulationBoundaryBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Expression.hxx>
#include <NXOpen/Features_ShipDesign_SteelInsulationBoundaryBuilder.hxx>
#include <NXOpen/GeometricUtilities_IComponentBuilder.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_features_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Features
    {
        namespace ShipDesign
        {
            class SteelInsulationBoundaryBuilder;
        }
    }
    class Expression;
    namespace GeometricUtilities
    {
        class IComponentBuilder;
    }
    class SelectNXObjectList;
    namespace Features
    {
        namespace ShipDesign
        {
            class _SteelInsulationBoundaryBuilderBuilder;
            class SteelInsulationBoundaryBuilderImpl;
            /**
                    Represents a Steel Insulation Boundary builder. The steel insulation boundary is used to collect boundary information that includes how much to offset the insulation from the selected boundary. 
                    The builder is used when creating/editing a @link NXOpen::Features::ShipDesign::SteelInsulation NXOpen::Features::ShipDesign::SteelInsulation@endlink  feature. 
                     <br> To create a new instance of this class, use @link NXOpen::Features::ShipDesign::SteelInsulationBuilder::CreateSteelInsulationBoundary  NXOpen::Features::ShipDesign::SteelInsulationBuilder::CreateSteelInsulationBoundary @endlink  <br> 
             <br>  Created in NX8.0.0.  <br>  
            */
            class NXOPENCPP_FEATURESEXPORT  SteelInsulationBoundaryBuilder : public NXOpen::TaggedObject, public virtual NXOpen::GeometricUtilities::IComponentBuilder
            {
                private: SteelInsulationBoundaryBuilderImpl * m_steelinsulationboundarybuilder_impl;
                private: friend class  _SteelInsulationBoundaryBuilderBuilder;
                protected: SteelInsulationBoundaryBuilder();
                public: ~SteelInsulationBoundaryBuilder();
                /**Returns  the face or edges that will be used to bound the insulation body. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::SelectNXObjectList * Boundaries
                (
                );
                /** Create offset expressions for each boundary. 
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : nx_ship_detail ("Ship Detail Design") */
                public: void CreateOffsetExpressions
                (
                );
                /** Get offset expressions for each boundary.  @return  boundary Offset Expressions.
                 <br>  Created in NX8.0.0.  <br>  
                 <br> License requirements : None */
                public: std::vector<NXOpen::Expression *> GetOffsetExpressions
                (
                );
                /** Validate whether the inputs to the component are sufficient for 
                            commit to be called.  If the component is not in a state to commit
                            then an exception is thrown.  For example, if the component requires
                            you to set some property, this method will throw an exception if
                            you haven't set it.  This method throws a not-yet-implemented
                            NXException for some components.
                         @return  Was self validation successful 
                 <br>  Created in NX3.0.1.  <br>  
                 <br> License requirements : None */
                public: virtual bool Validate
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
