#ifndef NXOpen_JAMTESTNAMESPACE_SUBSPACE_OMPPTAGGED2C_HXX_INCLUDED
#define NXOpen_JAMTESTNAMESPACE_SUBSPACE_OMPPTAGGED2C_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     JamTestNamespace_Subspace_OMPPTagged2c.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/JamTestNamespace_Subspace_OMPPTagged2.hxx>
#include <NXOpen/JamTestNamespace_Subspace_OMPPTagged2c.hxx>
#include <NXOpen/JamTestNamespace_Subspace_OMPPTagged2.hxx>
#include <NXOpen/libnxopenjamtestcpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace JamTestNamespace
    {
        namespace Subspace
        {
            class OMPPTagged2c;
        }
    }
    namespace JamTestNamespace
    {
        namespace Subspace
        {
            class OMPPTagged2;
        }
    }
    namespace JamTestNamespace
    {
        namespace Subspace
        {
            class _OMPPTagged2cBuilder;
            class OMPPTagged2cImpl;
            /** Test class for testing a class inside a nested namespace  <br> This is a testing class.  <br> 
             <br>  Created in NX4.0.0.  <br>  
            */
            class NXOPENJAMTESTCPPEXPORT  OMPPTagged2c : public NXOpen::JamTestNamespace::Subspace::OMPPTagged2
            {
                private: OMPPTagged2cImpl * m_ompptagged2c_impl;
                private: friend class  _OMPPTagged2cBuilder;
                protected: OMPPTagged2c();
                public: ~OMPPTagged2c();
                /** Test method  @return  
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: double DivideBy30
                (
                    int input /** input */ 
                );
                /** Returns a data struct  @return  
                 <br>  Created in NX4.0.0.  <br>  
                 <br> License requirements : None */
                public: NXOpen::JamTestNamespace::Subspace::OMPPTagged2::Struct1 GetStruct2
                (
                );
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
