#ifndef NXOpen_TOOLING_REUSABLEOBJECTMANAGER_HXX_INCLUDED
#define NXOpen_TOOLING_REUSABLEOBJECTMANAGER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Tooling_ReusableObjectManager.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/Tooling_ReusableObjectPasteBuilder.hxx>
#include <NXOpen/Tooling_ReusePositioningObjectBuilder.hxx>
#include <NXOpen/libnxopencpp_tooling_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Tooling
    {
        class ReusableObjectManager;
    }
    namespace Tooling
    {
        class ToolingManager;
    }
    namespace Tooling
    {
        class ReusableObjectPasteBuilder;
    }
    namespace Tooling
    {
        class ReusePositioningObjectBuilder;
    }
    namespace Tooling
    {
        class ReusableObjectManagerImpl;
        /** Represents a collection of ReusableObjects  <br> To obtain an instance of this class, refer to @link NXOpen::Tooling::ToolingManager  NXOpen::Tooling::ToolingManager @endlink  <br> 
         <br>  Created in NX8.0.0.  <br>  
        */
        class NXOPENCPP_TOOLINGEXPORT  ReusableObjectManager
        {
            private: ReusableObjectManagerImpl * m_reusableobjectmanager_impl;
            private: NXOpen::Tooling::ToolingManager* m_owner;
            /// \cond NX_NO_DOC 
            public: explicit ReusableObjectManager(NXOpen::Tooling::ToolingManager *owner);


            /// \endcond 
            public: 
            /**Returns the tag of this object.  */
            tag_t Tag() const; 
            public: ~ReusableObjectManager();
            /** Creates a ReusableObjectPasteBuilder  @return @link  Tooling::ReusableObjectPasteBuilder   Tooling::ReusableObjectPasteBuilder @endlink  object object 
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Tooling::ReusableObjectPasteBuilder * CreatePasteBuilder
            (
            );
            /** Creates a  @link NXOpen::Tooling::ReusePositioningObjectBuilder NXOpen::Tooling::ReusePositioningObjectBuilder@endlink   @return @link  Tooling::ReusePositioningObjectBuilder   Tooling::ReusePositioningObjectBuilder @endlink  object object 
             <br>  Created in NX11.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::Tooling::ReusePositioningObjectBuilder * CreatePositioningBuilder
            (
            );
        }; //lint !e1712 default constructor not defined for class  

    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
