#ifndef NXOpen_UNITCOLLECTION_HXX_INCLUDED
#define NXOpen_UNITCOLLECTION_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     UnitCollection.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <iterator>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/TaggedObjectCollection.hxx>
#include <NXOpen/TaggedObject.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    class UnitCollection;
    class BasePart;
    class Unit;
    class UnitCollectionImpl;
    /** Provides methods for manipulating the units in a part  <br> To obtain an instance of this class, refer to @link NXOpen::BasePart  NXOpen::BasePart @endlink  <br> 
     <br>  Created in NX4.0.0.  <br>  
    */
    class NXOPENCPPEXPORT  UnitCollection : public NXOpen::TaggedObjectCollection
    {
        private: UnitCollectionImpl * m_unitcollection_impl;
        private: NXOpen::BasePart* m_owner;
        /// \cond NX_NO_DOC 
        public: explicit UnitCollection(NXOpen::BasePart *owner);


        /// \endcond 
        public: 
        /**Returns the tag of this object.  */
        tag_t Tag() const; 
        public: ~UnitCollection();
        /** Iterator for accessing the contents of the collection. */
        //lint -sem(NXOpen::UnitCollection::iterator::copy,initializer)
        class iterator : public std::iterator<std::forward_iterator_tag, NXOpen::Unit *>
        {
        public:
            /** Default constructor */
            iterator() : m_context(NULL), m_current(NULL_TAG)
            {
                // coverity[uninit_member]
            } //lint !e1401 m_state is not initialized
            /// \cond NX_NO_DOC
            explicit iterator(NXOpen::UnitCollection *context) : m_context(context), m_current(NULL_TAG)
            {
                // coverity[uninit_member]
            }//lint !e1401 m_state is not initialized
            /// \endcond
            /** Copy constructor */
            iterator(const iterator &other): m_context(NULL), m_current(NULL_TAG)
            {
                copy(other);
            }
            /** Copy constructor */
            iterator &operator =(const iterator &other)
            {
                if (&other != this)
                    copy(other);
                return *this;
            }
            /** Tests if the iterator objects on the left side and the right side of the operator are equal. */
            bool operator ==(const iterator &other) const
            {
                return m_current == other.m_current && m_context == other.m_context;
            }
            /** Tests if the iterator objects on the left side and the right side of the operator are not equal. */
            bool operator !=(const iterator &other) const
            {
                return !operator == (other);
            }
            /** Return the element currently pointed to by the iterator. */
            NXOPENCPPEXPORT  value_type operator * ();
            /** Points the iterator to next element. */
            iterator & operator ++()
            {
                next();
                return *this;
            }
            /** Points the iterator to next element. */
            iterator operator ++(int)
            {
                iterator tmp(*this);
                ++*this;
                return tmp;
            }
        private:
            void copy(const iterator &other)
            {
                m_context = other.m_context;
                m_current = other.m_current;
                for (int i = 0; i < sizeof(m_state)/sizeof(m_state[0]); i++)
                     m_state[i] = other.m_state[i];
            }
            NXOPENCPPEXPORT  void next();
            NXOpen::UnitCollection *m_context;
            tag_t m_current;
            unsigned int m_state[8];
        };
        /** Returns an iterator addressing the first element. */
        iterator begin();
        /** Returns an iterator addressing one past the last element. */
        iterator end()
        {
            return iterator(this);
        }
        /** Finds the @link  Unit   Unit @endlink  with the given identifier as recorded in a journal. 
          An exception will be thrown if no object can be found with the given journal identifier.  @return  Unit found 
         <br>  Created in NX4.0.0.  <br>  
         <br> License requirements : None */
        public: NXOpen::Unit * FindObject
        (
            const NXString & journalIdentifier /** Identifier to be found */
        );
        /** Finds the @link  Unit   Unit @endlink  with the given identifier as recorded in a journal. 
          An exception will be thrown if no object can be found with the given journal identifier.  @return  Unit found 
         <br>  Created in NX4.0.0.  <br>  
         <br> License requirements : None */
        NXOpen::Unit * FindObject
        (
            const char * journalIdentifier /** Identifier to be found */
        );
        /** Finds the list of different types of measures available in the system.
           <br> Types of measures include length, area and volume <br>  @return  Array of names of measure types 
         <br>  Created in NX4.0.0.  <br>  
         <br> License requirements : None */
        public: std::vector<NXString> GetMeasures
        (
        );
        /** Finds the units that are available for a given type of measure  @return  Array of units for a given measurement type 
         <br>  Created in NX4.0.0.  <br>  
         <br> License requirements : None */
        public: std::vector<NXOpen::Unit *> GetMeasureTypes
        (
            const NXString & measureName /** the type of measure */
        );
        /** Finds the units that are available for a given type of measure  @return  Array of units for a given measurement type 
         <br>  Created in NX4.0.0.  <br>  
         <br> License requirements : None */
        std::vector<NXOpen::Unit *> GetMeasureTypes
        (
            const char * measureName /** the type of measure */
        );
        /** Find the base part unit for a given type of measure  @return  base unit 
         <br>  Created in NX4.0.0.  <br>  
         <br> License requirements : None */
        public: NXOpen::Unit * GetBase
        (
            const NXString & measureName /** the type of measure */
        );
        /** Find the base part unit for a given type of measure  @return  base unit 
         <br>  Created in NX4.0.0.  <br>  
         <br> License requirements : None */
        NXOpen::Unit * GetBase
        (
            const char * measureName /** the type of measure */
        );
        /** Convert a value from one unit of measure to another  @return  
         <br>  Created in NX4.0.0.  <br>  
         <br> License requirements : None */
        public: double Convert
        (
            NXOpen::Unit * initialUnit /** initial measurement unit */,
            NXOpen::Unit * targetUnit /** target measurement unit */,
            double initialValue /** initial value */ 
        );
    }; //lint !e1712 default constructor not defined for class  

}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
