#ifndef NXOpen_CAE_RESPONSESIMULATION_NODALFUNCTIONEXCITATION_HXX_INCLUDED
#define NXOpen_CAE_RESPONSESIMULATION_NODALFUNCTIONEXCITATION_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_ResponseSimulation_NodalFunctionExcitation.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_ResponseSimulation_Excitation.hxx>
#include <NXOpen/libnxopencpp_cae_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace CAE
    {
        namespace ResponseSimulation
        {
            class NodalFunctionExcitation;
        }
    }
    namespace CAE
    {
        namespace ResponseSimulation
        {
            class Excitation;
        }
    }
    namespace CAE
    {
        namespace ResponseSimulation
        {
            class _NodalFunctionExcitationBuilder;
            class NodalFunctionExcitationImpl;
            /** Represents the abstract class of nodal function excitation  <br> This is an abstract class, and cannot be created.  <br> 
             <br>  Created in NX5.0.0.  <br>  
            */
            class NXOPENCPP_CAEEXPORT  NodalFunctionExcitation : public NXOpen::CAE::ResponseSimulation::Excitation
            {
                /** the subtype of nodal function excitation */
                public: enum Type
                {
                    TypeNodalForce/** nodal force */ ,
                    TypeEnforcedMotion/** enforced motion */ 
                };

                private: NodalFunctionExcitationImpl * m_nodalfunctionexcitation_impl;
                private: friend class  _NodalFunctionExcitationBuilder;
                protected: NodalFunctionExcitation();
                public: ~NodalFunctionExcitation();
            };
        }
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
