#ifndef NXOpen_FEATURES_MESHSURFACE_HXX_INCLUDED
#define NXOpen_FEATURES_MESHSURFACE_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Features_MeshSurface.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Features_BodyFeature.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Features
    {
        class MeshSurface;
    }
    namespace Features
    {
        class BodyFeature;
    }
    namespace Features
    {
        class _MeshSurfaceBuilder;
        /** Represents a mesh surface feature. */
        class NXOPENCPPEXPORT MeshSurface : public Features::BodyFeature
        {
            private: friend class  _MeshSurfaceBuilder;
            protected: MeshSurface();
        };
    }
}
#undef EXPORTLIBRARY
#endif
