#ifndef NXOpen_CAE_BASEFEMODEL_HXX_INCLUDED
#define NXOpen_CAE_BASEFEMODEL_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_BaseFEModel.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_IFEModel.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace CAE
    {
        class BaseFEModel;
    }
    namespace CAE
    {
        class BeamSectionCollection;
    }
    namespace CAE
    {
        class CAEConnectionCollection;
    }
    namespace CAE
    {
        class IFEModel;
    }
    namespace CAE
    {
        class MeshControlCollection;
    }
    namespace CAE
    {
        class NodeElementManager;
    }
    namespace CAE
    {
        class _BaseFEModelBuilder;
        /**  @brief  This class represents an Assembly Finite Element Model.
                          This class will act as the gateway to the 
                          Finite Element Nodes (@link CAE::FENode CAE::FENode@endlink ) and Elements (@link CAE::FEElement CAE::FEElement@endlink ) in the model. 
                          Only one instance of this class will exist in each assyfem part file 

           <br> To obtain an instance of this class, use @link CAE::BaseFemPart::BaseFEModel CAE::BaseFemPart::BaseFEModel@endlink  <br> */
        class NXOPENCPPEXPORT BaseFEModel : public CAE::IFEModel
        {
            private: friend class  _BaseFEModelBuilder;
            protected: BaseFEModel();
            /** This method will update the finite element model so that it 
                        is in sync with any underlying changes.  All FE Meshes that 
                        are in the update pending state will be remeshed.
                     <br> License requirements : nx_masterfem ("Finite Element Modeling") */
            public: void UpdateFemodel
            (
            );


            private: NXOpen::CAE::BeamSectionCollection *beamSections;
            /** Returns the Beam Section collection belonging to the part */
            public: NXOpen::CAE::BeamSectionCollection *BeamSections()
            {
                return beamSections;
            }
            private: NXOpen::CAE::NodeElementManager *nodeElementMgr;
            /** Returns the node element manager belonging to this fem part */
            public: NXOpen::CAE::NodeElementManager *NodeElementMgr()
            {
                return nodeElementMgr;
            }
            private: NXOpen::CAE::CAEConnectionCollection *caeConnections;
            /** Returns the connection collector manager belonging to the part */
            public: NXOpen::CAE::CAEConnectionCollection *CaeConnections()
            {
                return caeConnections;
            }
            private: NXOpen::CAE::MeshControlCollection *meshControls;
            /** Returns the mesh control collection belonging to this fem part */
            public: NXOpen::CAE::MeshControlCollection *MeshControls()
            {
                return meshControls;
            }
            public: virtual void initialize();
        };
    }
}
#undef EXPORTLIBRARY
#endif
