#ifndef NXOpen_VALIDATIONENTERPRISEIDENTIFICATIONVALIDATOR_HXX_INCLUDED
#define NXOpen_VALIDATIONENTERPRISEIDENTIFICATIONVALIDATOR_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     ValidationEnterpriseIdentificationValidator.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/ValidationAnnotationValidator.hxx>
#include <NXOpen/libnxopendebugsessioncpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    class ValidationEnterpriseIdentificationValidator;
    class ValidationAnnotationValidator;
    class _ValidationEnterpriseIdentificationValidatorBuilder;
    class ValidationEnterpriseIdentificationValidatorImpl;
    /** validator for a Enterprise Identification  <br> This is a test class.  <br> 
     <br>  Created in NX8.0.0.  <br>  
    */
    class NXOPENDEBUGSESSIONCPPEXPORT  ValidationEnterpriseIdentificationValidator : public NXOpen::ValidationAnnotationValidator
    {
        private: ValidationEnterpriseIdentificationValidatorImpl * m_validationenterpriseidentificationvalidator_impl;
        private: friend class  _ValidationEnterpriseIdentificationValidatorBuilder;
        protected: ValidationEnterpriseIdentificationValidator();
        public: ~ValidationEnterpriseIdentificationValidator();
    };
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
