#ifndef NXOpen_CAE_PROPERTYTABLE_HXX_INCLUDED
#define NXOpen_CAE_PROPERTYTABLE_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_PropertyTable.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_BeamSectionOptions.hxx>
#include <NXOpen/CAE_MaterialOptions.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/ScalarMatrixValue.hxx>
#include <NXOpen/ScalarTableValue.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace CAE
    {
        class PropertyTable;
    }
    class Axis;
    namespace CAE
    {
        class BeamSectionOptions;
    }
    namespace CAE
    {
        class MaterialOptions;
    }
    namespace CAE
    {
        class NamedPropertyTable;
    }
    class CoordinateSystem;
    class Direction;
    class Expression;
    namespace Fields
    {
        class FieldExpression;
    }
    namespace Fields
    {
        class FieldWrapper;
    }
    namespace Fields
    {
        class ScalarFieldWrapper;
    }
    namespace Fields
    {
        class VectorFieldWrapper;
    }
    class NXObject;
    class Point;
    class ScalarMatrixValue;
    class ScalarTableValue;
    namespace CAE
    {
        class _PropertyTableBuilder;
        /**  @brief  Represents a property table  

           <br> This is a sub object <br> */
        class NXOPENCPPEXPORT PropertyTable : public NXObject
        {
            private: friend class  _PropertyTableBuilder;
            protected: PropertyTable();
            /**The count of properties in the table  @return  count of properties  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: int GetPropertyCount
            (
            );
            /** Returns the name of the property  @return  name of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXString GetPropertyNameByIndex
            (
                int index /** index of the property */
            );
            /** Returns the string value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXString GetStringPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the string value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetStringPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const NXString & propertyValue /** value of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Returns the text value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: std::vector<NXString> GetTextPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the text value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetTextPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                std::vector<NXString> & propertyValue /** value of the property */
            );
            /** Returns the boolean value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: bool GetBooleanPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the boolean value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetBooleanPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                bool propertyValue /** value of the property */
            );
            /** Returns the integer value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: int GetIntegerPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the integer value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetIntegerPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                int propertyValue /** value of the property */
            );
            /** Returns the double value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: double GetDoublePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the double value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetDoublePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                double propertyValue /** value of the property */
            );
            /** Returns the expression @link Expression Expression@endlink  value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::Expression * GetScalarPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the expression @link Expression Expression@endlink  value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetScalarPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Expression * propertyValue /** value of the property */
            );
            /** Returns the field expression @link Fields::FieldExpression Fields::FieldExpression@endlink  value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::Fields::FieldExpression * GetScalarFieldPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the field expression @link Fields::FieldExpression Fields::FieldExpression@endlink  value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetScalarFieldPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Fields::FieldExpression * propertyValue /** value of the property */
            );
            /** Returns the direction @link Direction Direction@endlink  value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::Direction * GetVectorPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the direction @link Direction Direction@endlink  value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetVectorPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Direction * propertyValue /** value of the property */
            );
            /** Returns the coordinate system @link CoordinateSystem CoordinateSystem@endlink  
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::CoordinateSystem * GetCoordinateSystemPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the coordinate system @link CoordinateSystem CoordinateSystem@endlink 
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetCoordinateSystemPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::CoordinateSystem * propertyValue /** value of the property */
            );
            /** Returns the referenced object value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::NXObject * GetReferencePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the referenced object value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetReferencePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::NXObject * propertyValue /** value of the property 
                                                                                            The object passed in can be of the following types 
                                                                                            @link CAE::CAEVertex CAE::CAEVertex@endlink 
                                                                                            @link CAE::CAEEdge CAE::CAEEdge@endlink 
                                                                                            @link CAE::CAEFace CAE::CAEFace@endlink 
                                                                                            @link CAE::CAEBody CAE::CAEBody@endlink 
                                                                                          */
            );
            /** Returns the point value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::Point * GetPointPropertyValue
            (
                const NXString & propertyName /** name of the property    <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the point value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetPointPropertyValue
            (
                const NXString & propertyName /** name of the property    <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Point * propertyValue /** value of the property */
            );
            /** Returns the scalar array value of the property
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: std::vector<double> GetScalarArrayPropertyValue
            (
                const NXString & propertyName /** name of the property    <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the scalar array value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetScalarArrayPropertyValue
            (
                const NXString & propertyName /** name of the property    <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const std::vector<double> & propertyValue /** value of the property */
            );
            /** Returns the date time value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void GetDateTimePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                int* propertyYear /** year of the property */,
                int* propertyMonth /** month of the property */,
                int* propertyDay /** day of the property */,
                int* propertyHour /** hour of the property */,
                int* propertyMin /** minute of the property */,
                int* propertySecond /** second of the property */,
                int* propertyMsec /** milisecond of the property */
            );
            /** Returns the date time value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetDateTimePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                int propertyYear /** year of the property */,
                int propertyMonth /** month of the property */,
                int propertyDay /** day of the property */,
                int propertyHour /** hour of the property */,
                int propertyMin /** minute of the property */,
                int propertySecond /** second of the property */,
                int propertyMsec /** milisecond of the property */
            );
            /** Returns the referenced array object value of the property
                      @return   <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: std::vector<NXOpen::CAE::NamedPropertyTable *> GetNamedPropertyTableArrayPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the referenced object array value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetNamedPropertyTableArrayPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const std::vector<NXOpen::CAE::NamedPropertyTable *> & propertyValue /** property value */ 
            );
            /** Returns the integer array value of the property
                      @return   <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: std::vector<int> GetIntegerArrayPropertyValue
            (
                const NXString & propertyName /**   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the integer array value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetIntegerArrayPropertyValue
            (
                const NXString & propertyName /**    <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                const std::vector<int> & propertyValue /** property value */ 
            );
            /** Returns the referenced referenced named property table object value of the property
                      @return  Value of Named Proeprty Table Reference  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::CAE::NamedPropertyTable * GetNamedPropertyTablePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the referenced named property table object value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetNamedPropertyTablePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::CAE::NamedPropertyTable * namedPropertyTable /** value of the property 
                                                                                            The object passed in can be of the following types 
                                                                                            @link CAE::PhysicalPropertyTable CAE::PhysicalPropertyTable@endlink  
                                                                                            @link CAE::Laminate CAE::Laminate@endlink 
                                                                                          */
            );
            /** Returns the axis @link Axis Axis@endlink 
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::Axis * GetAxisPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the axis @link Axis Axis@endlink 
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetAxisPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Axis * propertyValue /** value of the property */
            );
            /** Returns the  material options @link CAE::MaterialOptions CAE::MaterialOptions@endlink 
                      @return  material options  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::CAE::MaterialOptions * GetPhysicalMaterialPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the material options @link CAE::MaterialOptions CAE::MaterialOptions@endlink 
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetPhysicalMaterialPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::CAE::MaterialOptions * materialOptions /** material options */
            );
            /** Returns the  beam section options @link CAE::BeamSectionOptions CAE::BeamSectionOptions@endlink 
                      @return  material options  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::CAE::BeamSectionOptions * GetCaeSectionPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the beam section options @link CAE::BeamSectionOptions CAE::BeamSectionOptions@endlink 
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetCaeSectionPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::CAE::BeamSectionOptions * beamSectionOptions /** material options */
            );
            /** Returns the field wrapper @link Fields::FieldWrapper Fields::FieldWrapper@endlink  
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::Fields::FieldWrapper * GetFieldWrapperPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the field wrapper @link Fields::FieldWrapper Fields::FieldWrapper@endlink 
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetFieldWrapperPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Fields::FieldWrapper * propertyValue /** value of the property */
            );
            /** Returns the scalar field wrapper @link Fields::ScalarFieldWrapper Fields::ScalarFieldWrapper@endlink  
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::Fields::ScalarFieldWrapper * GetScalarFieldWrapperPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the scalar field wrapper @link Fields::ScalarFieldWrapper Fields::ScalarFieldWrapper@endlink 
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetScalarFieldWrapperPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Fields::ScalarFieldWrapper * propertyValue /** value of the property */
            );
            /** Returns the vector field wrapper @link Fields::VectorFieldWrapper Fields::VectorFieldWrapper@endlink  
                      @return  value of the property  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::Fields::VectorFieldWrapper * GetVectorFieldWrapperPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Sets the vector field wrapper @link Fields::VectorFieldWrapper Fields::VectorFieldWrapper@endlink 
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetVectorFieldWrapperPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::Fields::VectorFieldWrapper * propertyValue /** value of the property */
            );
            /** Returns a matrix cell value from the matrix value of the property
                      @return  NxM Scalar matrix  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::ScalarMatrixValue * GetMatrixPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Set a matrix cell value from the matrix value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetMatrixPropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::ScalarMatrixValue * matrix /** NxM Scalar matrix */
            );
            /** Returns a scalar table value value from the scalar table value of the property
                      @return  NxM Scalar table  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: NXOpen::ScalarTableValue * GetScalarTablePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */
            );
            /** Set a scalar table value from the scalar table value of the property
                      <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetScalarTablePropertyValue
            (
                const NXString & propertyName /** name of the property   <br>  NOTE: The full Unicode character set is not supported for this parameter.  <br> */,
                NXOpen::ScalarTableValue * table /** NxM Scalar table */
            );
        };
    }
}
#undef EXPORTLIBRARY
#endif
