#ifndef NXOpen_ANNOTATIONS_BOLTCIRCLECENTERLINEBUILDER_HXX_INCLUDED
#define NXOpen_ANNOTATIONS_BOLTCIRCLECENTERLINEBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Annotations_BoltCircleCenterlineBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Annotations_CircleCenterlineBuilder.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace Annotations
    {
        class BoltCircleCenterlineBuilder;
    }
    namespace Annotations
    {
        class CircleCenterlineBuilder;
    }
    namespace Annotations
    {
        class _BoltCircleCenterlineBuilderBuilder;
        /** Represents a BoltCircleCenterlineBuilder Builder  <br> To create a new instance of this class, use @link Annotations::CenterlineCollection::CreateBoltCircleCenterlineBuilder Annotations::CenterlineCollection::CreateBoltCircleCenterlineBuilder@endlink  <br> 
        Default values:
        FullCircle: true
        Type: Through3Points
        */
        class NXOPENCPPEXPORT BoltCircleCenterlineBuilder : public Annotations::CircleCenterlineBuilder
        {
            private: friend class  _BoltCircleCenterlineBuilderBuilder;
            protected: BoltCircleCenterlineBuilder();
        };
    }
}
#undef EXPORTLIBRARY
#endif
