#ifndef NXOpen_CAE_CAESET_HXX_INCLUDED
#define NXOpen_CAE_CAESET_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     CAE_CAESet.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/CAE_SetObject.hxx>
#include <NXOpen/CAE_SetTargetObject.hxx>
#include <NXOpen/TransientObject.hxx>
#include <NXOpen/libnxopencpp_exports.hxx>
namespace NXOpen
{
    namespace CAE
    {
        class CAESet;
    }
    class NXObject;
    namespace CAE
    {
        /**  @brief  Represents a group of CAE object sets. The objects in each set
                can be used to create loads, constraints ..etc 

           <br> To create a new instance of this class, use @link CAE::SetManager::CreateCaeSet CAE::SetManager::CreateCaeSet@endlink  <br> */
        class NXOPENCPPEXPORT CAESet : public TransientObject
        {
            public: explicit CAESet(void *ptr);
            /** This method is deprecated. Use @link SetMembers SetMembers@endlink  instead.
                        Sets the objects in the set. 
             @deprecated Deprecated in NX4.0.1 <br> 
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetObjects
            (
                const std::vector<NXOpen::CAE::SetTargetObject> & objects /** objects to add to set */
            );
            /** This method is deprecated. Use @link GetMembers GetMembers@endlink  instead.
                        Gets the objects in the set. 
             @deprecated Deprecated in NX4.0.1 <br> 
             <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void GetObjects
            (
                std::vector<NXOpen::CAE::SetTargetObject> & objects /** objects in set */
            );
            /** Sets the objects in the set.  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void SetMembers
            (
                const std::vector<NXOpen::CAE::SetObject> & members /** objects to add to set */
            );
            /** Gets the objects in the set.  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: void GetMembers
            (
                std::vector<NXOpen::CAE::SetObject> & members /** objects in set */
            );
            /** Destroys the set  <br> License requirements : nx_masterfem ("Finite Element Modeling") OR nx_design_sim ("NX Design Simulation") */
            public: virtual ~CAESet();
        };
    }
}
#undef EXPORTLIBRARY
#endif
