#ifndef NXOpen_VALIDATIONTDPFORMFIELDVALIDATOR_HXX_INCLUDED
#define NXOpen_VALIDATIONTDPFORMFIELDVALIDATOR_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     ValidationTDPFormFieldValidator.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/ValidationTDPBaseRectangleValidator.hxx>
#include <NXOpen/libnxopendebugsessioncpp_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    class ValidationTDPFormFieldValidator;
    class ValidationTDPBaseRectangleValidator;
    class _ValidationTDPFormFieldValidatorBuilder;
    class ValidationTDPFormFieldValidatorImpl;

    /// \cond NX_NO_DOC 
    /** tdp form field validator  <br> This is a test class.  <br> 
     <br>  Created in NX2007.0.0.  <br>  
    */
    class NXOPENDEBUGSESSIONCPPEXPORT  ValidationTDPFormFieldValidator : public NXOpen::ValidationTDPBaseRectangleValidator
    {
        private: ValidationTDPFormFieldValidatorImpl * m_validationtdpformfieldvalidator_impl;
        private: friend class  _ValidationTDPFormFieldValidatorBuilder;
        protected: ValidationTDPFormFieldValidator();
        public: ~ValidationTDPFormFieldValidator();
    };

    /// \endcond 
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
